/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pos.hire.view;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.concurrent.TimeUnit;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pos.hire.Controller.CarController;
import pos.hire.Controller.CustomerController;
import pos.hire.Controller.RentalDetailController;
import pos.hire.Dto.CarDto;
import pos.hire.Dto.CustomerDto;
import pos.hire.Dto.RentalDetailDto;

/**
 *
 * @author BIMSARA
 */
public class AddHirePanel extends javax.swing.JPanel {
 private List<RentalDetailDto> rentalDetailDtos = new ArrayList<>();
    private CarController carController;
    private CustomerController customerController;
    private RentalDetailController rentalDetailController;
    
    //private RentalController rentalController;
    /**
     * Creates new form AddHireForm
     */
    public AddHirePanel() {
        carController = new CarController();
        customerController = new CustomerController();
        rentalDetailController = new RentalDetailController();
        
        initComponents();
        loadAllCars();
        loadAllCustomers();
        //loadAllHires();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        basePanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        headerlabel = new javax.swing.JLabel();
        formPanel = new javax.swing.JPanel();
        carIdLabel = new javax.swing.JLabel();
        rentSLabel = new javax.swing.JLabel();
        rentSText = new javax.swing.JTextField();
        perDayRentLabel = new javax.swing.JLabel();
        perDayRentText = new javax.swing.JTextField();
        rentELabel = new javax.swing.JLabel();
        rentText = new javax.swing.JTextField();
        totalLabel = new javax.swing.JLabel();
        totalText = new javax.swing.JTextField();
        advLabel = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        usernameLabel = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        advText = new javax.swing.JTextField();
        searchcarButton1 = new javax.swing.JButton();
        carDataLabel = new javax.swing.JLabel();
        returnCheckBox = new javax.swing.JCheckBox();
        balenceText = new javax.swing.JTextField();
        refundText = new javax.swing.JTextField();
        idText = new javax.swing.JTextField();
        refundLabel = new javax.swing.JLabel();
        balanceLabel = new javax.swing.JLabel();
        date1Label = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        calButton = new javax.swing.JButton();
        balButton = new javax.swing.JButton();
        formPanel1 = new javax.swing.JPanel();
        custIdLabel = new javax.swing.JLabel();
        rentidLabel = new javax.swing.JLabel();
        rentidText = new javax.swing.JTextField();
        usernameLabel1 = new javax.swing.JLabel();
        idLabel1 = new javax.swing.JLabel();
        searchcustButton = new javax.swing.JButton();
        custDataLabel = new javax.swing.JLabel();
        custIdText = new javax.swing.JTextField();
        clearButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        carTable = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        custTable = new javax.swing.JTable();

        headerlabel.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        headerlabel.setText("Add Hire");
        headerlabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        headerlabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        formPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        carIdLabel.setText("Car Id");

        rentSLabel.setText("Rent Start Date");

        rentSText.setColumns(2);
        rentSText.setToolTipText("YYYY-MM-DD");
        rentSText.setActionCommand("<Not Set>");

        perDayRentLabel.setText("Per Day Rent");

        rentELabel.setText("Rent End Date");

        totalLabel.setText("Total Amount");

        advLabel.setText("Advance Pay");

        addButton.setText("Place Rent");
        addButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        searchcarButton1.setText("Search");
        searchcarButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchcarButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchcarButton1ActionPerformed(evt);
            }
        });

        carDataLabel.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N

        returnCheckBox.setText("Return");
        returnCheckBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        returnCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnCheckBoxActionPerformed(evt);
            }
        });

        idText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextActionPerformed(evt);
            }
        });

        refundLabel.setText("Refund");

        balanceLabel.setText("Balence");

        date1Label.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        date1Label.setText("( YYYY-MM-DD )");

        dateLabel.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        dateLabel.setText("( YYYY-MM-DD )");

        calButton.setText("Calculate");
        calButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        calButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calButtonActionPerformed(evt);
            }
        });

        balButton.setText("Balance");
        balButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        balButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout formPanelLayout = new javax.swing.GroupLayout(formPanel);
        formPanel.setLayout(formPanelLayout);
        formPanelLayout.setHorizontalGroup(
            formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formPanelLayout.createSequentialGroup()
                        .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(refundText, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(formPanelLayout.createSequentialGroup()
                                .addComponent(totalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(totalText, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rentSText, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(advText, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(idText, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(7, 7, 7)
                        .addComponent(calButton)
                        .addGap(49, 49, 49)
                        .addComponent(returnCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(formPanelLayout.createSequentialGroup()
                        .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(refundLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(formPanelLayout.createSequentialGroup()
                                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(formPanelLayout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(carIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(rentSLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(119, 119, 119)
                                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(formPanelLayout.createSequentialGroup()
                                        .addComponent(searchcarButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(idLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(formPanelLayout.createSequentialGroup()
                                                .addGap(122, 122, 122)
                                                .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(formPanelLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(carDataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(formPanelLayout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(formPanelLayout.createSequentialGroup()
                                                .addComponent(balanceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(8, 8, 8)
                                                .addComponent(balenceText, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(balButton))
                                            .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(formPanelLayout.createSequentialGroup()
                                                .addComponent(perDayRentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(4, 4, 4)
                                                .addComponent(perDayRentText, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(formPanelLayout.createSequentialGroup()
                                                .addComponent(rentELabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(rentText, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addComponent(advLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(date1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 104, Short.MAX_VALUE)))
                .addContainerGap())
        );
        formPanelLayout.setVerticalGroup(
            formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPanelLayout.createSequentialGroup()
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formPanelLayout.createSequentialGroup()
                        .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(carIdLabel)
                            .addComponent(searchcarButton1)
                            .addComponent(idText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rentSLabel)
                            .addComponent(rentSText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rentELabel)
                            .addComponent(rentText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(formPanelLayout.createSequentialGroup()
                        .addComponent(usernameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(carDataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(3, 3, 3)
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(advLabel)
                    .addComponent(advText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(perDayRentLabel)
                    .addComponent(perDayRentText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(refundLabel)
                    .addComponent(refundText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(balanceLabel)
                    .addComponent(balenceText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(balButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(totalLabel)
                        .addComponent(totalText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addButton)
                        .addComponent(calButton))
                    .addComponent(returnCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        formPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        custIdLabel.setText("Custormer Id");

        rentidLabel.setText("Rent Id");

        searchcustButton.setText("Search");
        searchcustButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchcustButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchcustButtonActionPerformed(evt);
            }
        });

        custDataLabel.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N

        custIdText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custIdTextActionPerformed(evt);
            }
        });

        clearButton.setText("Reset");
        clearButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout formPanel1Layout = new javax.swing.GroupLayout(formPanel1);
        formPanel1.setLayout(formPanel1Layout);
        formPanel1Layout.setHorizontalGroup(
            formPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formPanel1Layout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(usernameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(formPanel1Layout.createSequentialGroup()
                        .addComponent(rentidLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rentidText, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(idLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(custIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(formPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(formPanel1Layout.createSequentialGroup()
                                .addComponent(custIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(searchcustButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(clearButton))
                            .addGroup(formPanel1Layout.createSequentialGroup()
                                .addComponent(custDataLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())))))
        );
        formPanel1Layout.setVerticalGroup(
            formPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPanel1Layout.createSequentialGroup()
                .addGroup(formPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formPanel1Layout.createSequentialGroup()
                        .addComponent(usernameLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(formPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(formPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(custIdLabel)
                                .addComponent(searchcustButton)
                                .addComponent(custIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(clearButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(formPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(formPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rentidLabel)
                            .addComponent(rentidText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(custDataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        carTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        carTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        carTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(carTable);

        custTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        custTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        custTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                custTableMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(custTable);

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(headerlabel, javax.swing.GroupLayout.DEFAULT_SIZE, 811, Short.MAX_VALUE)
                    .addComponent(formPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, headerPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(formPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addComponent(headerlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout basePanelLayout = new javax.swing.GroupLayout(basePanel);
        basePanel.setLayout(basePanelLayout);
        basePanelLayout.setHorizontalGroup(
            basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basePanelLayout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        basePanelLayout.setVerticalGroup(
            basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(basePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(basePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        placeHire();// addUser();
    }//GEN-LAST:event_addButtonActionPerformed

    private void searchcarButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchcarButton1ActionPerformed
        searchCars(); // TODO add your handling code here:
    }//GEN-LAST:event_searchcarButton1ActionPerformed

    private void returnCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnCheckBoxActionPerformed
        returned();// TODO add your handling code here:
    }//GEN-LAST:event_returnCheckBoxActionPerformed

    private void idTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTextActionPerformed

    private void calButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calButtonActionPerformed
        calTotal();// TODO add your handling code here:
    }//GEN-LAST:event_calButtonActionPerformed

    private void balButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balButtonActionPerformed
        calBalance();// TODO add your handling code here:
    }//GEN-LAST:event_balButtonActionPerformed

    private void searchcustButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchcustButtonActionPerformed
        searchCust();// TODO add your handling code here:
    }//GEN-LAST:event_searchcustButtonActionPerformed

    private void custIdTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custIdTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custIdTextActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        clearHire();// TODO add your handling code here:
    }//GEN-LAST:event_clearButtonActionPerformed

    private void carTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carTableMouseClicked
        searchCar();//searchUser();
    }//GEN-LAST:event_carTableMouseClicked

    private void custTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_custTableMouseClicked
        searchCustomer();// TODO add your handling code here:
    }//GEN-LAST:event_custTableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JLabel advLabel;
    private javax.swing.JTextField advText;
    private javax.swing.JButton balButton;
    private javax.swing.JLabel balanceLabel;
    private javax.swing.JTextField balenceText;
    private javax.swing.JPanel basePanel;
    private javax.swing.JButton calButton;
    private javax.swing.JLabel carDataLabel;
    private javax.swing.JLabel carIdLabel;
    private javax.swing.JTable carTable;
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel custDataLabel;
    private javax.swing.JLabel custIdLabel;
    private javax.swing.JTextField custIdText;
    private javax.swing.JTable custTable;
    private javax.swing.JLabel date1Label;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JPanel formPanel;
    private javax.swing.JPanel formPanel1;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel headerlabel;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel idLabel1;
    private javax.swing.JTextField idText;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel perDayRentLabel;
    private javax.swing.JTextField perDayRentText;
    private javax.swing.JLabel refundLabel;
    private javax.swing.JTextField refundText;
    private javax.swing.JLabel rentELabel;
    private javax.swing.JLabel rentSLabel;
    private javax.swing.JTextField rentSText;
    private javax.swing.JTextField rentText;
    private javax.swing.JLabel rentidLabel;
    private javax.swing.JTextField rentidText;
    private javax.swing.JCheckBox returnCheckBox;
    private javax.swing.JButton searchcarButton1;
    private javax.swing.JButton searchcustButton;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JTextField totalText;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JLabel usernameLabel1;
    // End of variables declaration//GEN-END:variables
private void loadAllCars() {
        try {
            String[] collumns = {"carId",  "Brand", "PricePerDay", "Availability", "CategoryId"};
            DefaultTableModel dtm = new DefaultTableModel(collumns, 0) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };
            carTable.setModel(dtm);

            ArrayList<CarDto> cars = carController.getAllCars();

           for (CarDto car : cars) {
            if (car.getAvailability()) { // Check if the car is available
                String availability = "available";
                Object[] rowData = {car.getId(), car.getBrand(), car.getPricePerDay(),car.getCategoryid(), availability};
                dtm.addRow(rowData);
            }
        }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(CarPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

private void searchCar() {
        try {
            String carId = carTable.getValueAt(carTable.getSelectedRow(), 0).toString();
            CarDto carDto = carController.getCar(carId);

            if (carDto != null) {
                idText.setText(carDto.getId());
                perDayRentText.setText(Double.toString(carDto.getPricePerDay()));
                

                loadAllCars();
            } else {
                JOptionPane.showMessageDialog(this, "Car Not Found");
            }

        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(EditCarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

 private void loadAllCustomers() {

         try {
        String[] columns = {"CustId", "Name", "Nic"};
        DefaultTableModel dtm = new DefaultTableModel(columns, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        custTable.setModel(dtm);

        ArrayList<CustomerDto> customers = customerController.getAllCustomers();

         for (CustomerDto customer : customers) {
            // Check if the customer has an active hire (you need to implement this method)
            if (!customerHasActiveHire(customer.getId())) {
                Object[] rowData = {customer.getId(), customer.getName(), customer.getNic()};
                dtm.addRow(rowData);
            }
        }
    } catch (Exception ex) {
        java.util.logging.Logger.getLogger(CustomerPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(this, ex.getMessage());
    }
    }
 
 private void searchCustomer() {
        try {
            String custId = custTable.getValueAt(custTable.getSelectedRow(), 0).toString();
            CustomerDto customerDto = customerController.getCustomer(custId);

            if (customerDto != null) {
                custIdText.setText(customerDto.getId());
                

            } else {
                JOptionPane.showMessageDialog(this, "Customer Not Found");
            }

        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(CustomerPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

  private void searchCust() {
        try {
            String custId = custIdText.getText();
            CustomerDto cust = customerController.getCustomer(custId);
            if (cust != null) {
                custDataLabel.setText(cust.getName() + ", " + cust.getNic());
            } else {
                JOptionPane.showMessageDialog(this, "Customer Not Found");
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(CustomerPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    private void searchCars() {
        try {
            String carId = idText.getText();
            CarDto car = carController.getCar(carId);
            if (car != null) {
                 String availability = car.getAvailability() ? "available" : "not available";
            carDataLabel.setText(availability + ", " + car.getPricePerDay());
            } else {
                JOptionPane.showMessageDialog(this, "Customer Not Found");
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(CustomerPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    private void placeHire() {
        try {
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            Date rentDate = dateFormat.parse(rentSText.getText());
            Date rentDate1 = dateFormat.parse(rentText.getText());

            long timeDifference = Math.abs(rentDate1.getTime() - rentDate.getTime());
            long daysDifference = TimeUnit.DAYS.convert(timeDifference, TimeUnit.MILLISECONDS);

            if (daysDifference > 30) {
                JOptionPane.showMessageDialog(this, "Rental period cannot exceed 30 days.");
                return; // Exit the method if the rental period is too long
            }
            String carId = idText.getText();
            if (carId == null || carId.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Car ID cannot be empty.");
                return;
            }

            String custId = custIdText.getText();
            if (custId == null || custId.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Customer ID cannot be empty.");
                return;
            }
            double perDayRent = Double.parseDouble(perDayRentText.getText());

            // Calculate the total amount
            double totalAmount = perDayRent * daysDifference;

            double advancedPayment = Double.parseDouble(advText.getText());

            // Calculate the balance amount
            double balanceAmount = totalAmount - advancedPayment;
            //String carId = idText.getText();
            if (!isCarAvailableForHire(carId, rentDate, rentDate1)) {
                updateCarAvailability(idText.getText(), false);
                JOptionPane.showMessageDialog(this, "The selected car is not available for hire during the specified period.");
                return;
            } else {
                if (customerHasActiveHire(custIdText.getText())) {
                    JOptionPane.showMessageDialog(this, "Customer already has an active hire.");
                    return;
                }
            }

            RentalDetailDto rentalDetailDto = new RentalDetailDto(
                    rentidText.getText(),
                    Double.parseDouble(advText.getText()),
                    balanceAmount,
                    perDayRent,
                    Double.parseDouble(refundText.getText()),
                    rentDate1,
                    rentDate,
                    returnCheckBox.isSelected(),
                    totalAmount,
                    carId,
                    custId
            );
            int dialogResult = JOptionPane.showConfirmDialog(this, "Do you want to Place Hire?", "Confirm Rental", JOptionPane.YES_NO_OPTION);

            if (dialogResult == JOptionPane.YES_OPTION) {

                String result = rentalDetailController.addHire(rentalDetailDto);

                if (result != null && result.equals("Success")) {

                    JOptionPane.showMessageDialog(this, "Hire placed successfully.");
                    clear();
                } else {
                    updateCarAvailability(idText.getText(), false);
                    JOptionPane.showMessageDialog(this, "Hire placed successfully.");
                    clear();
                    loadAllCars();
                    loadAllCustomers();
                }
            } else {
                clear();
            }

        } catch (ParseException ex) {
            java.util.logging.Logger.getLogger(CustomerPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Error parsing date: " + ex.getMessage());
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(CustomerPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }
    private boolean customerHasActiveHire(String id) {
        try {
            return rentalDetailController.hasActiveHire(id);
        } catch (Exception ex) {

            ex.printStackTrace();
            return false;
        }
    }

    private boolean isCarAvailableForHire(String carId, Date rentDate, Date rentDate1) {
        try {
            return rentalDetailController.isCarAvailableForHire(carId, rentDate, rentDate1);

        } catch (Exception ex) {
            ex.printStackTrace();
            return false;
        }
    }

    private void returned() {
        try {
        // Check if the return checkbox is selected
        if (returnCheckBox.isSelected()) {
            String carId = idText.getText();
            // Update the car availability to "available"
            updateCarAvailability(carId, true);
            
            // Clear the hire-related fields
            clearHire();
            
            // Allow the customer to place a new hire
            //enableHireFields(true);
            
            // Reset the return checkbox to unselected
            returnCheckBox.setSelected(true);
        }
    } catch (Exception ex) {
        java.util.logging.Logger.getLogger(CustomerPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(this, ex.getMessage());
    }   }

    private void clear() {
        rentidText.setText("");
        advText.setText("");
        balenceText.setText("");
        custIdText.setText("");
        idText.setText("");
        perDayRentText.setText("");
        refundText.setText("");

        rentText.setText("");
        rentSText.setText("");
        returnCheckBox.setSelected(false);
        totalText.setText("");
    }

    private void clearHire() {
         rentidText.setText("");
        advText.setText("");
        balenceText.setText("");
        custIdText.setText("");
        idText.setText("");
        perDayRentText.setText("");
        refundText.setText("");

        rentText.setText("");
        rentSText.setText("");
        returnCheckBox.setSelected(false);
        totalText.setText("");
    }

    private void calTotal() {
        try {
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        Date rentDate = dateFormat.parse(rentSText.getText());
        Date rentDate1 = dateFormat.parse(rentText.getText());

        long timeDifference = Math.abs(rentDate1.getTime() - rentDate.getTime());
        long daysDifference = TimeUnit.DAYS.convert(timeDifference, TimeUnit.MILLISECONDS);

        if (daysDifference > 30) {
            JOptionPane.showMessageDialog(this, "Rental period cannot exceed 30 days.");
            return; // Exit the method if the rental period is too long
        }

        double perDayRent = Double.parseDouble(perDayRentText.getText());

        // Calculate the total amount
        double totalAmount = perDayRent * daysDifference;

        // Display the total amount in the totalTextFeild
        totalText.setText(String.format("%.2f", totalAmount)); // Assuming totalTextFeild is a JTextField

    } catch (ParseException ex) {
        java.util.logging.Logger.getLogger(CustomerPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(this, "Error parsing date: " + ex.getMessage());
    } catch (Exception ex) {
        java.util.logging.Logger.getLogger(CustomerPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(this, ex.getMessage());
    }
}

    private void calBalance() {
         try {
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        Date rentDate = dateFormat.parse(rentSText.getText());
        Date rentDate1 = dateFormat.parse(rentText.getText());

        long timeDifference = Math.abs(rentDate1.getTime() - rentDate.getTime());
        long daysDifference = TimeUnit.DAYS.convert(timeDifference, TimeUnit.MILLISECONDS);

        if (daysDifference > 30) {
            JOptionPane.showMessageDialog(this, "Rental period cannot exceed 30 days.");
            return; // Exit the method if the rental period is too long
        }

        double perDayRent = Double.parseDouble(perDayRentText.getText());

        // Calculate the total amount
        double totalAmount = perDayRent * daysDifference;
        
         double advancedPayment = Double.parseDouble(advText.getText());
        
        // Calculate the balance amount
        double balanceAmount = totalAmount - advancedPayment;

        // Display the total amount in the totalTextFeild
        balenceText.setText(String.format("%.2f", balanceAmount)); // Assuming totalTextFeild is a JTextField

    } catch (ParseException ex) {
        java.util.logging.Logger.getLogger(CustomerPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(this, "Error parsing date: " + ex.getMessage());
    } catch (Exception ex) {
        java.util.logging.Logger.getLogger(CustomerPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(this, ex.getMessage());
    }
    }

    private void updateCarAvailability(String Id, boolean isAvailability) {
       try {
        // Assuming you have a method in your CarController to update car availability
        carController.updateCarAvailability(Id, isAvailability);
    } catch (Exception ex) {
        // Handle any exceptions if the update fails
        ex.printStackTrace();
    }   }

   
    }

   

 

   
